@extends('layouts.admin')

@section('title', 'Availability & Pricing Setup')

@section('content')
    <div class="content-area flex-grow-1">
        <div class="header d-flex justify-content-between align-items-center">
            <h2 class="mb-0">Availability & Pricing Setup</h2>
        </div>
        <div class="row availability-calendar-container">
            <div class="col-lg-8 mb-4">
                <div class="card p-4">
                    <div class="mb-3">
                        <label for="selectPackage" class="form-label">Select Package</label>
                        <select id="selectPackage" class="form-select">
                            @foreach ($packages as $package)
                                <option value="{{ $package->id }}" data-type="{{ $package->type ?? 'regular' }}"
                                    {{ $package->id === $defaultPackage->id ? 'selected' : '' }}>
                                    {{ $package->name }}
                                </option>
                            @endforeach
                        </select>

                    </div>
                    <!-- Two Month Calendar Layout -->
                    <div class="calendar-container">
                        <!-- First Month -->
                        <div class="calendar-month">
                            <div class="calendar-header">
                                <span class="calendar-nav-arrow" onclick="calendarManager.previousMonth()">‹</span>
                                <h5 class="mb-0" id="currentMonth">{{ $currentMonth }}</h5>
                                <span class="calendar-nav-arrow" onclick="calendarManager.nextMonth()">›</span>
                            </div>
                            <div class="calendar-grid mb-4" id="calendarGrid">
                                {{-- Calendar dates will be generated by JavaScript --}}
                            </div>
                        </div>

                        <!-- Second Month -->
                        <div class="calendar-month">
                            <div class="calendar-header">
                                <h5 class="mb-0" id="nextMonth">{{ $currentMonth }}</h5>
                            </div>
                            <div class="calendar-grid mb-4" id="calendarGridNext">
                                {{-- Second month calendar dates will be generated by JavaScript --}}
                            </div>
                        </div>
                    </div>
                    <div class="d-flex flex-wrap mt-3 justify-content-center justify-content-md-start">
                        <div class="legend-item"><span class="legend-dot bg-primary"></span> Today</div>
                        <div class="legend-item"><span class="legend-dot bg-booked"></span> Booked</div>
                        <div class="legend-item"><span class="legend-dot bg-info"></span> Selected</div>
                        <div class="legend-item"><span class="legend-dot bg-secondary"></span> No Booking</div>
                        <div class="legend-item"><span class="legend-dot bg-success"></span> Premium Price</div>
                        <div class="legend-item"><span class="legend-dot bg-discounted"></span> Discounted Price</div>
                            <div class="legend-item"><span class="legend-dot bg-range"></span> Range Selection</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="actions-panel">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h4 class="mb-0">Actions</h4>
                        <div>
                            <button type="button" class="btn btn-sm btn-outline-primary me-2" onclick="testApi()">Test
                                API</button>
                            <button type="button" class="btn-close"></button>
                        </div>
                    </div>

                    <form id="availabilityForm">
                        <p class="text-muted">Date: <span id="selectedDate">Select a date</span></p>

                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <span class="fw-bold">Day Off</span>
                            <div class="form-check form-switch">
                                <input class="form-check-input" type="checkbox" id="dayOffSwitch" name="is_day_off">
                            </div>
                        </div>

                        {{-- ATV/UTV tabs removed - vehicle types are determined by package selection --}}

                        <div class="card mb-3 p-3 bg-light">
                            <div class="d-flex justify-content-between align-items-center">
                                <span id="capacityLabel">Available Capacity <small
                                        class="text-success">(Dynamic)</small></span>
                                <div class="d-flex align-items-center">
                                    <input type="number" class="form-control form-control-sm input-compact"
                                        id="availableVehicles" name="capacity_total" value="10" min="0">
                                    <span class="text-muted ms-2 clickable"
                                        title="Dynamic capacity based on package type">🔄</span>
                                </div>
                            </div>
                        </div>

                        <div class="row g-2 mb-4">
                            <div class="col-6">
                                <div class="card p-3 bg-light text-center">
                                    <small>Booked Slots</small>
                                    <span class="fw-bold" id="bookedSlots">0</span>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="card p-3 bg-light text-center">
                                    <small>Available Slots</small>
                                    <span class="fw-bold" id="availableSlots">0</span>
                                </div>
                            </div>
                        </div>

                        <div class="card mb-3 p-3" style="display: none;">
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <span class="fw-bold">Time Slots</span>
                                <div class="d-flex align-items-center gap-2">
                                    <select id="slotPresetSelect" class="form-select form-select-sm" style="width:auto">
                                        <option value="">Default preset</option>
                                    </select>
                                    <small class="text-muted">Manage per-slot availability</small>
                                </div>
                            </div>
                            <div id="slotControls"></div>
                        </div>

                        <!-- Range Selection Controls -->
                        <div class="card mb-3 p-3 bg-light">
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <span class="fw-bold">Date Range Selection</span>
                                <button type="button" class="btn btn-warning btn-sm" id="rangeSelectionToggle">
                                    Exit Range Selection
                                </button>
                            </div>
                            <div id="rangeSelectionInfo" class="text-muted small" style="display: none;">
                                <!-- Range info will be populated by JavaScript -->
                            </div>
                            <button type="button" class="btn btn-success btn-sm mt-2" id="applyToRangeButton" 
                                    onclick="calendarManager.applyPricingToRange()" style="display: none;">
                                Apply to Range
                            </button>
                        </div>

                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <span class="fw-bold">Set Special Price</span>
                            <div class="form-check form-switch">
                                <input class="form-check-input" type="checkbox" id="specialPriceSwitch"
                                    name="special_price_enabled">
                            </div>
                        </div>

                        <div class="price-field" style="display: none;">
                            <div class="mb-3">
                                <div class="btn-group w-100" role="group">
                                    <input type="radio" class="btn-check" name="priceOption" id="premiumPrice"
                                        value="premium" autocomplete="off">
                                    <label
                                        class="btn btn-outline-secondary d-flex justify-content-between align-items-center"
                                        for="premiumPrice">
                                        Premium Price
                                        <span>✓</span>
                                    </label>

                                    <input type="radio" class="btn-check" name="priceOption" id="discountedPrice"
                                        value="discounted" autocomplete="off" checked>
                                    <label
                                        class="btn btn-outline-secondary d-flex justify-content-between align-items-center"
                                        for="discountedPrice">
                                        Discounted Price
                                        <span>✓</span>
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="pricing-section-container">
                            <div id="weekdayPricingSection">
                                <div class="d-flex justify-content-between align-items-center mb-3">
                                    <h3 class="mb-0">Weekdays Pricing <span id="weekdayRangeIndicator" class="badge bg-info ms-2" style="display: none;">Range</span></h3>
                                    <a href="#" class="text-decoration-none text-orange fw-bold reset-link"
                                        onclick="event.preventDefault(); calendarManager.resetPricing('weekday')">Reset</a>
                                </div>

                                <div id="weekdayPricingCards">
                                    {{-- Will be populated by JavaScript --}}
                                </div>
                            </div>

                            <div id="weekendPricingSection">
                                <div class="d-flex justify-content-between align-items-center mb-3">
                                    <h3 class="mb-0">Weekend Pricing <span id="weekendRangeIndicator" class="badge bg-info ms-2" style="display: none;">Range</span></h3>
                                    <a href="#" class="text-decoration-none text-orange fw-bold reset-link"
                                        onclick="event.preventDefault(); calendarManager.resetPricing('weekend')">Reset</a>
                                </div>

                                <div id="weekendPricingCards">
                                    {{-- Will be populated by JavaScript --}}
                                </div>
                            </div>
                        </div>

                        {{-- Removed Update Availability button since we use on-change updating methods --}}
                    </form>
                </div>
            </div>
        </div>
    </div>

    <style>
        /* Loading States */
        .loading {
            opacity: 0.7;
            pointer-events: none;
            position: relative;
        }

        .loading::after {
            content: '';
            position: absolute;
            top: 50%;
            left: 50%;
            width: 30px;
            height: 30px;
            margin: -15px 0 0 -15px;
            border: 3px solid #f3f3f3;
            border-top: 3px solid #007bff;
            border-radius: 50%;
            animation: spin 1s linear infinite;
            z-index: 1000;
        }

        /* Enhanced loading for specific areas */
        .calendar-container.loading::after {
            background: rgba(255, 255, 255, 0.8);
            border-radius: 8px;
        }

        /* Special pricing indicator */
        .special-price-indicator {
            font-size: 0.75rem;
            color: #FC692A;
            font-weight: 500;
            margin-top: 2px;
        }

        /* Special pricing container */
        .special-price-container {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
        }

        .special-price {
            color: #FC692A !important;
        }

        /* Crossed out original price */
        .original-price-crossed {
            font-size: 0.9rem;
            color: #6c757d;
            text-decoration: line-through;
            margin-top: -5px;
            margin-bottom: 2px;
        }

        /* Regular pricing container */
        .regular-price-container {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
        }

        /* Pricing card editing states */
        .pricing-card.editing .price-display {
            cursor: pointer;
        }

        .pricing-card:not(.editing) .edit-icon {
            display: none !important;
        }

        /* Edit icon styling */
        .edit-icon {
            font-size: 16px;
            color: #6c757d;
            cursor: pointer;
            transition: color 0.2s ease;
            display: inline-block;
        }

        .edit-icon:hover {
            color: #495057;
        }

        .edit-icon.d-none {
            display: none !important;
        }

        /* Ensure edit icon is visible when special pricing is enabled */
        .pricing-card .edit-icon:not(.d-none) {
            display: inline-block !important;
            visibility: visible !important;
            opacity: 1 !important;
        }

        .pricing-section-container.loading::after {
            background: rgba(255, 255, 255, 0.8);
            border-radius: 8px;
        }

        #availabilityForm.loading::after {
            background: rgba(255, 255, 255, 0.8);
            border-radius: 8px;
        }

        @keyframes spin {
            0% {
                transform: rotate(0deg);
            }

            100% {
                transform: rotate(360deg);
            }
        }

        /* Global Loading Overlay */
        #globalLoadingOverlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.5);
            display: flex;
            justify-content: center;
            align-items: center;
            z-index: 9999;
        }

        .loading-overlay {
            background: white;
            padding: 2rem;
            border-radius: 8px;
            text-align: center;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .loading-spinner {
            display: flex;
            flex-direction: column;
            align-items: center;
        }



        /* Hide all check icons by default */
        .btn-outline-secondary .fas.fa-check {
            display: none;
        }

        /* Show the check icon only when the corresponding radio is checked */
        .btn-check:checked+.btn-outline-secondary .fas.fa-check {
            display: inline-block;
        }

        /* Calendar date styles */
        .calendar-grid {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            gap: 2px;
        }

        .calendar-grid .day-name {
            text-align: center;
            font-weight: bold;
            padding: 8px;
            color: #666;
        }

        .calendar-grid .date {
            text-align: center;
            padding: 8px;
            cursor: pointer;
            border-radius: 4px;
            position: relative;
            transition: background-color 0.2s;
        }

        .calendar-grid .date:hover:not(.disabled) {
            background-color: #f8f9fa;
        }

        .calendar-grid .date.disabled {
            color: #ccc;
            cursor: not-allowed;
        }


        /* Updated color scheme to match design exactly */
        .calendar-grid .date.selected {
            background-color: #0dcaf0 !important;
            color: white !important;
        }

        .calendar-grid .date.today {
            background-color: #007bff !important;
            color: white;
        }

        /* Two Month Calendar Layout */
        .calendar-container {
            display: flex;
            gap: 20px;
            justify-content: space-between;
        }

        .calendar-month {
            flex: 1;
        }



        /* Booked dates - orange text */
        .calendar-grid .date.booked {
            background-color: transparent !important;
            color: #ff6600 !important;
        }

        /* Modified state for available vehicles input */
        #availableVehicles.modified {
            border-color: #ffc107 !important;
            box-shadow: 0 0 0 0.2rem rgba(255, 193, 7, 0.25);
        }

        #availableVehicles.modified:focus {
            border-color: #ffc107 !important;
            box-shadow: 0 0 0 0.2rem rgba(255, 193, 7, 0.25);
        }

        /* Premium dates - green text (higher priority than selected) */
        .calendar-grid .date.premium {
            background-color: transparent !important;
            color: #28a745 !important;
            font-weight: bold !important;
        }

        /* Discounted dates - purple text (higher priority than selected) */
        .calendar-grid .date.discounted {
            background-color: transparent !important;
            color: #6f42c1 !important;
            font-weight: bold !important;
        }

        /* Special price classes should override selected class */
        .calendar-grid .date.selected.premium {
            background-color: transparent !important;
            color: #28a745 !important;
            font-weight: bold !important;
            border: 2px solid #007bff !important;
            border-radius: 4px !important;
        }

        .calendar-grid .date.selected.discounted {
            background-color: transparent !important;
            color: #6f42c1 !important;
            font-weight: bold !important;
            border: 2px solid #007bff !important;
            border-radius: 4px !important;
        }

        /* Day off dates - gray text */
        .calendar-grid .date.day-off {
            background-color: transparent !important;
            color: #6c757d !important;
            font-weight: bold !important;
        }

        /* Day-off dates - gray */
        .calendar-grid .date.day-off {
            background-color: #6c757d !important;
            color: white !important;
        }

        /* Available dates - light gray background */
        .calendar-grid .date:not(.disabled):not(.today):not(.selected):not(.booked):not(.premium):not(.discounted):not(.day-off) {
            background-color: #f8f9fa !important;
            color: #333 !important;
        }

        /* Test styles to ensure colors are working */
        .calendar-grid .date.test-red {
            background-color: #dc3545 !important;
            color: white !important;
        }

        .calendar-grid .date.test-blue {
            background-color: #007bff !important;
            color: white !important;
        }

        .date-indicator {
            position: absolute;
            bottom: 2px;
            left: 50%;
            transform: translateX(-50%);
            width: 4px;
            height: 4px;
            border-radius: 50%;
            background-color: currentColor;
        }

        /* Legend styles */
        .legend-item {
            display: flex;
            align-items: center;
            margin-right: 15px;
            margin-bottom: 5px;
            font-size: 14px;
        }

        .legend-dot {
            width: 12px;
            height: 12px;
            border-radius: 50%;
            margin-right: 5px;
        }

        /* Custom legend dot colors */
        .bg-booked {
            background-color: #ff6600 !important;
        }

        .bg-discounted {
            background-color: #6f42c1 !important;
        }

        .bg-range {
            background-color: #007bff !important;
        }

        .legend-color {
            width: 12px;
            height: 12px;
            border-radius: 2px;
            margin-right: 5px;
        }

        /* Pricing card image styles */
        .pricing-card img {
            max-width: 100%;
            height: auto;
            display: block !important;
            visibility: visible !important;
        }

        .pricing-card-header img {
            display: block !important;
            visibility: visible !important;
            opacity: 1 !important;
        }

        .pricing-card-header i.fas.fa-motorcycle {
            display: none;
            font-size: 40px;
            color: #FC692A;
        }

        @keyframes spin {
            from {
                transform: rotate(0deg);
            }

            to {
                transform: rotate(360deg);
            }
        }

        /* Time-slot controls - match admin look */
        #slotControls .slot-list {
            display: flex;
            flex-direction: column;
            gap: 10px;
        }

        #slotControls .slot-item {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 12px 14px;
            border: 1px solid #eee;
            border-radius: 10px;
            background: #fff;
        }

        #slotControls .slot-item .slot-title {
            font-weight: 600;
        }

        #slotControls .slot-item .slot-stats {
            font-size: 12px;
            color: #6c757d;
            margin-top: 2px;
        }

        #slotControls .slot-actions {
            display: flex;
            align-items: center;
            gap: 10px;
        }

        #slotControls .slot-actions .form-control {
            width: 80px;
        }

        /* Orange switch to match brand */
        #slotControls .form-switch.slot-switch .form-check-input {
            width: 2.4em;
            height: 1.2em;
            background-color: #e9ecef;
            border-color: #e9ecef;
            cursor: pointer;
        }

        #slotControls .form-switch.slot-switch .form-check-input:checked {
            background-color: #FC692A;
            border-color: #FC692A;
        }

        #slotControls .form-switch.slot-switch .form-check-input:focus {
            box-shadow: 0 0 0 0.2rem rgba(252, 105, 42, 0.25);
        }

        /* Enhanced Range Selection Styles */
        .calendar-grid .date.range-start {
            background-color: #007bff !important;
            color: white !important;
            border: 3px solid #0056b3 !important;
            position: relative;
            font-weight: bold !important;
            box-shadow: 0 2px 4px rgba(0, 123, 255, 0.3) !important;
        }

        .calendar-grid .date.range-start::after {
            content: "START";
            position: absolute;
            right: 1px;
            top: 1px;
            font-weight: bold;
            font-size: 8px;
            background: rgba(255, 255, 255, 0.2);
            padding: 1px 2px;
            border-radius: 2px;
        }

        .calendar-grid .date.range-end {
            background-color: #007bff !important;
            color: white !important;
            border: 3px solid #0056b3 !important;
            position: relative;
            font-weight: bold !important;
            box-shadow: 0 2px 4px rgba(0, 123, 255, 0.3) !important;
        }

        .calendar-grid .date.range-end::after {
            content: "END";
            position: absolute;
            left: 1px;
            top: 1px;
            font-weight: bold;
            font-size: 8px;
            background: rgba(255, 255, 255, 0.2);
            padding: 1px 2px;
            border-radius: 2px;
        }

        .calendar-grid .date.range-middle {
            background-color: #007bff !important;
            color: white !important;
            border: 2px solid #0056b3 !important;
            position: relative;
            font-weight: bold !important;
            box-shadow: 0 2px 4px rgba(0, 123, 255, 0.3) !important;
        }

        .calendar-grid .date.range-middle::before {
            content: "";
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: linear-gradient(45deg, transparent 30%, rgba(255, 255, 255, 0.1) 50%, transparent 70%);
            pointer-events: none;
        }

        /* Enhanced hover effect for range dates */
        .calendar-grid .date.range-start:hover,
        .calendar-grid .date.range-end:hover,
        .calendar-grid .date.range-middle:hover {
            background-color: #0056b3 !important;
            transform: scale(1.05);
            transition: all 0.2s ease;
        }

        /* Range selection info styling */
        #rangeSelectionInfo {
            font-size: 0.875rem;
            padding: 8px 12px;
            background-color: #f8f9fa;
            border: 1px solid #dee2e6;
            border-radius: 4px;
            margin-top: 8px;
        }

        /* Range selection button states */
        #rangeSelectionToggle.btn-warning {
            background-color: #ffc107;
            border-color: #ffc107;
            color: #212529;
        }

        #rangeSelectionToggle.btn-warning:hover {
            background-color: #e0a800;
            border-color: #d39e00;
        }

        /* Apply to range button */
        #applyToRangeButton {
            width: 100%;
            font-weight: 600;
        }

        /* Range selection card */
        .card.bg-light .fw-bold {
            color: #495057;
        }
    </style>

    @push('scripts')
        <script src="{{ asset('admin/js/calendar-manager.js') }}"></script>
        <script>
            // Test API function
            async function testApi() {
                try {
                    const csrfToken = document.querySelector('meta[name="csrf-token"]')?.content;
                    console.log('CSRF Token:', csrfToken);

                    const response = await fetch('/admin/calendar/test-api', {
                        method: 'GET',
                        headers: {
                            'Accept': 'application/json',
                            'X-CSRF-TOKEN': csrfToken
                        },
                        credentials: 'same-origin'
                    });

                    console.log('Response status:', response.status);
                    console.log('Response headers:', response.headers);

                    if (response.ok) {
                        const data = await response.json();
                        console.log('API Test Success:', data);
                        alert('API is working! User: ' + data.user);
                    } else {
                        console.error('API Test Failed:', response.status, response.statusText);
                        alert('API test failed: ' + response.status);
                    }
                } catch (error) {
                    console.error('API Test Error:', error);
                    alert('API test error: ' + error.message);
                }
            }
        </script>
    @endpush
@endsection
